export const GET_TRADIE_PROFILE_DATA = 'GET_TRADIE_PROFILE_DATA';
export const SET_TRADIE_PROFILE_DATA = 'SET_TRADIE_PROFILE_DATA';

export const GET_BANK_DETAILS_START = 'GET_BANK_DETAILS_START';
export const GET_BANK_DETAILS_END = 'GET_BANK_DETAILS_END';

export const ADD_BANK_DETAILS_START = 'ADD_BANK_DETAILS_START';
export const ADD_BANK_DETAILS_END = 'ADD_BANK_DETAILS_END';

export const UPDATE_BANK_DETAILS_START = 'UPDATE_BANK_DETAILS_START';
export const UPDATE_BANK_DETAILS_END = 'UPDATE_BANK_DETAILS_END';
