export const GET_SEARCH_JOB_LIST = 'GET_SEARCH_JOB_LIST';
export const SET_SEARCH_JOB_LIST = 'SET_SEARCH_JOB_LIST';
export const GET_JOB_TYPE_LIST = 'GET_JOB_TYPE_LIST'; 
export const SET_JOB_TYPE_LIST = 'SET_JOB_TYPE_LIST'; 

export const FETCH_FAILED = 'FETCH_FAILED';