
export const EDIT_MILESTONE_ID = 'EDIT_MILESTONE_ID'
export const EDIT_MILESTONE_TIMINGS = 'EDIT_MILESTONE_TIMINGS'
export const EDIT_DETAIL_SCREEN = 'EDIT_DETAIL_SCREEN'
export const FETCH_HOME_BUILDER = 'FETCH_HOME_BUILDER'
export const SET_FETCH_HOME_BUILDER = 'SET_FETCH_HOME_BUILDER'
export const SET_LOCAL_CHANGES = 'SET_LOCAL_CHANGES';
export const GET_LOCAL_CHANGES = 'GET_LOCAL_CHANGES';