export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED'
export const REQUEST_API_DATA = 'REQUEST_API_DATA'
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA'
export const FAILED_API_DATA = 'FAILED_API_DATA'



